import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { AvatarHeader } from "./_components/header/avatar";
import { NavigationMenuHeader } from "./_components/header/navigationMenu";
import "./globals.css";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="flex justify-between mx-2 my-1 bg-slate-50 ">
          <NavigationMenuHeader />
          <AvatarHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
